namespace AdventOfCode.Year2025.Tests;

public class Day7Tests
{
    private static string s_input = @".......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............";

    [Test]
    public void CountNumberOfBeamSplits_ReturnsExpectedResult()
    {
        string[] inputLines = GetInputLines(s_input);

        var result = Day7.CountNumberOfBeamSplits(inputLines);
        result.Should().Be(21);
    }

    [Test]
    public void SolvePart2_ReturnsExpectedResult()
    {
        string[] inputLines = GetInputLines(s_input);

        var result = Day7.GetNumberOfTimelines(inputLines);
        result.Should().Be(40);
    }

    private static string[] GetInputLines(string input) => input.Split(Environment.NewLine);
}
